service: server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  hello:
    handler: src/functions/hello.handler
    events: 
      - http:
          method: get
          path: hello